import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Agent from "../lib/agent";
import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";

const todosAgent = new Agent("@matt/todos");

export default function Home() {
  const router = useRouter();
  const [newListDraft, setNewListDraft] = useState("");
  const [lists, setLists] = useState([]);
  useEffect(() => {
    (async () => {
      const allLists = await todosAgent.getView("lists", {});
      setLists(allLists);
    })();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Todo Lists</h1>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          router.push("/" + newListDraft);
          setNewListDraft("");
        }}
      >
        <input
          placeholder="New list"
          value={newListDraft}
          onChange={(e) => setNewListDraft(e.target.value)}
        />
        <button>Create</button>
      </form>
      <br />
      {lists.map((listId) => {
        return (
          <Link key={listId} href={`/${listId}`}>
            <div
              style={{
                border: "1px solid darkgray",
                textAlign: "left",
                width: "300px",
                padding: "10px",
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
                cursor: "pointer",
              }}
            >
              <span>{listId ?? "Unamed"}</span>
              <span>👉</span>
            </div>
          </Link>
        );
      })}
    </div>
  );
}
